### ISSUE TITLE
Events not received on Windows 10

### ISSUE THREAD

**Issue by CbbK** [tuarua/DesktopToastANE#12]
Hi,
Before everything i'm fairly new to using ANE so maybe I did something wrong but I can't get any interactions with the toasts, they are shown but no events are returned to the app. Here's what I did :
On Flash CS6, Windows 10, with the latest Air SDK (25.0.0.134), I created a new project, added the ANE taken from the repository (DesktopToastANE/native_extension/ane/DesktopToastANE.ane)
Then wrote a minimal app :

```
import com.tuarua.DesktopToastANE;
import com.tuarua.toast.ToastEvent;
import com.tuarua.toast.constants.ToastActivationType;
import com.tuarua.toast.windows.ToastText;
import com.tuarua.toast.windows10.ToastAction;
import com.tuarua.toast.windows10.ToastInput;
import com.tuarua.toast.windows10.Toast10;
import com.tuarua.windows10;

use namespace windows10;

var toaster:DesktopToastANE = new DesktopToastANE();
trace("toaster.supportedNamespace", toaster.supportedNamespace);
toaster.init(NativeApplication.nativeApplication.applicationID, "Test ANE");

NativeApplication.nativeApplication.addEventListener(Event.EXITING, function(e:Event) {
	trace("Exit");
	toaster.dispose();
});

toaster.addEventListener(ToastEvent.TOAST_CLICKED, function(e:ToastEvent) {
	trace("TOAST_CLICKED", e);
});
toaster.addEventListener(ToastEvent.TOAST_DISMISSED, function(e:ToastEvent) {
	trace("TOAST_DISMISSED", e);
});
toaster.addEventListener(ToastEvent.TOAST_ERROR, function(e:ToastEvent) {
	trace("TOAST_ERROR", e);
});
toaster.addEventListener(ToastEvent.TOAST_HIDDEN, function(e:ToastEvent) {
	trace("TOAST_HIDDEN", e);
});
toaster.addEventListener(ToastEvent.TOAST_NOT_ACTIVATED, function(e:ToastEvent) {
	trace("TOAST_NOT_ACTIVATED", e);
});
toaster.addEventListener(ToastEvent.TOAST_TIMED_OUT, function(e:ToastEvent) {
	trace("TOAST_TIMED_OUT", e);
});


var xml:XML = XML(<toast launch="app-defined-string">
                        <visual>
                            <binding template="ToastGeneric">
                                <text>Test title</text>
                                <text>Test line</text>
                            </binding>
                        </visual>
                        <actions>
                            <action activationType="foreground" content="See more details" arguments="see"/>
                            <action activationType="foreground" content="Dismiss" arguments="dismiss"/>
                        </actions>
                    </toast>
);
toaster.createFromXML(xml);
toaster.show();		
```

The notification is displayed, with the right options and text but whenever I click one button, closes it or wait for time out none of the events in the code are triggered.
I have tried to organize the code in a class but that didn't change anything.

**Comment by tuarua** [comment]
Hi,
I am getting the same problem now too.
I may have broken something with my last commit. Investigating now

**Comment by tuarua** [comment]
This should be fixed now. Pull latest master

**Comment by CbbK** [comment]
Thank you for your reactivity. TOAST_DISMISSED and TOAST_TIMEOUT work now, but no TOAST_CLICKED yet. I tried creating the toast through XML or object and got the same result. If you want I can test an ANE if you can send me one before commiting it, thanks.

**Comment by tuarua** [comment]
Strange. Everything is fine for me (including clicks) using the example included with the project. 
I've checked again this morning.

**Comment by CbbK** [comment]
I just installed the Flex SDK and Starling to compile your example and it worked. I rewrote the code bit by bit and managed to get it to work in my project as well. Strange still that the code above still doesn't work.
Anyway, thanks!

**Comment by tuarua** [comment]
One thing you could look at is to ensure you don't call ane.init until you are sure your main Sprite is activated and added to stage.
It's been a while since I used Flex but here is the pure as3
`this.addEventListener(Event.ACTIVATE, onActivated);`
 
Also, Toasts actually create a .lnk to your exe in \AppData\Roaming\Microsoft\Windows\Start Menu\Programs . They do this to activate a COM. 
See whether that is created for your example.
